import ExcelJS from 'exceljs';
import { formatCurrency, formatDate } from './utils';
import path from 'path';
import fs from 'fs';

interface ReportOptions {
    title: string;
    collegeName: string;
    departmentName: string;
    dateRange: string;
    generatedBy: string;
    generatedAt: string;
}

interface BudgetData {
    budget_date: string;
    name: string;
    category_name: string | null;
    amount: number;
    source: string | null;
    payment_method: string;
    status: string;
}

interface ExpenseData {
    expense_date: string;
    name: string;
    amount: number;
    budget_name: string | null;
    category_name: string | null;
    spender: string | null;
    payment_method: string;
    status: string;
}

export async function generateBudgetReportExcel(
    data: BudgetData[],
    options: ReportOptions
): Promise<Buffer> {
    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet('Budget Report');

    // Set column widths
    worksheet.columns = [
        { width: 15 }, // Date
        { width: 30 }, // Name
        { width: 20 }, // Category
        { width: 15 }, // Amount
        { width: 20 }, // Source
        { width: 15 }, // Payment Method
        { width: 12 }, // Status
    ];

    // Add logo placeholder and header
    const logoPath = path.join(process.cwd(), 'public', 'logo.jpg');
    if (fs.existsSync(logoPath)) {
        const logoId = workbook.addImage({
            filename: logoPath,
            extension: 'jpeg',
        });
        worksheet.addImage(logoId, {
            tl: { col: 0, row: 0 },
            ext: { width: 80, height: 80 },
        });
    }

    // College Name (merged cells)
    worksheet.mergeCells('B1:G1');
    const collegeCell = worksheet.getCell('B1');
    collegeCell.value = options.collegeName;
    collegeCell.font = { bold: true, size: 16 };
    collegeCell.alignment = { horizontal: 'center', vertical: 'middle' };

    // Department Name
    worksheet.mergeCells('B2:G2');
    const deptCell = worksheet.getCell('B2');
    deptCell.value = options.departmentName;
    deptCell.font = { bold: true, size: 12 };
    deptCell.alignment = { horizontal: 'center', vertical: 'middle' };

    // Report Title
    worksheet.mergeCells('A4:G4');
    const titleCell = worksheet.getCell('A4');
    titleCell.value = options.title;
    titleCell.font = { bold: true, size: 14 };
    titleCell.alignment = { horizontal: 'center' };

    // Date Range
    worksheet.mergeCells('A5:G5');
    const dateRangeCell = worksheet.getCell('A5');
    dateRangeCell.value = `Period: ${options.dateRange}`;
    dateRangeCell.alignment = { horizontal: 'center' };

    // Add headers row
    const headerRow = worksheet.addRow(['Date', 'Name', 'Category', 'Amount', 'Source', 'Payment Method', 'Status']);
    headerRow.eachCell((cell) => {
        cell.font = { bold: true };
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1E3A5F' } };
        cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
        cell.alignment = { horizontal: 'center' };
        cell.border = {
            top: { style: 'thin' },
            left: { style: 'thin' },
            bottom: { style: 'thin' },
            right: { style: 'thin' },
        };
    });

    // Add data rows
    let totalAmount = 0;
    for (const item of data) {
        const row = worksheet.addRow([
            formatDate(item.budget_date, 'dd MMM yyyy'),
            item.name,
            item.category_name || '-',
            Number(item.amount),
            item.source || '-',
            item.payment_method,
            item.status,
        ]);
        totalAmount += Number(item.amount);

        row.eachCell((cell, colNumber) => {
            cell.border = {
                top: { style: 'thin' },
                left: { style: 'thin' },
                bottom: { style: 'thin' },
                right: { style: 'thin' },
            };
            if (colNumber === 4) {
                cell.numFmt = '₹#,##0.00';
            }
        });
    }

    // Add total row
    worksheet.addRow([]);
    const totalRow = worksheet.addRow(['', '', 'Total:', totalAmount, '', '', '']);
    totalRow.getCell(3).font = { bold: true };
    totalRow.getCell(4).font = { bold: true };
    totalRow.getCell(4).numFmt = '₹#,##0.00';

    // Footer
    worksheet.addRow([]);
    worksheet.addRow([`Generated by: ${options.generatedBy}`]);
    worksheet.addRow([`Generated on: ${options.generatedAt}`]);

    const buffer = await workbook.xlsx.writeBuffer();
    return Buffer.from(buffer);
}

export async function generateExpenseReportExcel(
    data: ExpenseData[],
    options: ReportOptions
): Promise<Buffer> {
    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet('Expense Report');

    // Set column widths
    worksheet.columns = [
        { width: 15 }, // Date
        { width: 30 }, // Name
        { width: 15 }, // Amount
        { width: 25 }, // Against Budget
        { width: 20 }, // Category
        { width: 20 }, // Spender
        { width: 15 }, // Payment Method
        { width: 12 }, // Status
    ];

    // Add logo
    const logoPath = path.join(process.cwd(), 'public', 'logo.jpg');
    if (fs.existsSync(logoPath)) {
        const logoId = workbook.addImage({
            filename: logoPath,
            extension: 'jpeg',
        });
        worksheet.addImage(logoId, {
            tl: { col: 0, row: 0 },
            ext: { width: 80, height: 80 },
        });
    }

    // College Name
    worksheet.mergeCells('B1:H1');
    const collegeCell = worksheet.getCell('B1');
    collegeCell.value = options.collegeName;
    collegeCell.font = { bold: true, size: 16 };
    collegeCell.alignment = { horizontal: 'center', vertical: 'middle' };

    // Department Name
    worksheet.mergeCells('B2:H2');
    const deptCell = worksheet.getCell('B2');
    deptCell.value = options.departmentName;
    deptCell.font = { bold: true, size: 12 };
    deptCell.alignment = { horizontal: 'center', vertical: 'middle' };

    // Report Title
    worksheet.mergeCells('A4:H4');
    const titleCell = worksheet.getCell('A4');
    titleCell.value = options.title;
    titleCell.font = { bold: true, size: 14 };
    titleCell.alignment = { horizontal: 'center' };

    // Date Range
    worksheet.mergeCells('A5:H5');
    const dateRangeCell = worksheet.getCell('A5');
    dateRangeCell.value = `Period: ${options.dateRange}`;
    dateRangeCell.alignment = { horizontal: 'center' };

    // Headers
    const headerRow = worksheet.addRow(['Date', 'Name', 'Amount', 'Against Budget', 'Category', 'Spender', 'Payment Method', 'Status']);
    headerRow.eachCell((cell) => {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1E3A5F' } };
        cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
        cell.alignment = { horizontal: 'center' };
        cell.border = {
            top: { style: 'thin' },
            left: { style: 'thin' },
            bottom: { style: 'thin' },
            right: { style: 'thin' },
        };
    });

    // Data rows
    let totalAmount = 0;
    for (const item of data) {
        const row = worksheet.addRow([
            formatDate(item.expense_date, 'dd MMM yyyy'),
            item.name,
            Number(item.amount),
            item.budget_name || '-',
            item.category_name || '-',
            item.spender || '-',
            item.payment_method,
            item.status,
        ]);
        totalAmount += Number(item.amount);

        row.eachCell((cell, colNumber) => {
            cell.border = {
                top: { style: 'thin' },
                left: { style: 'thin' },
                bottom: { style: 'thin' },
                right: { style: 'thin' },
            };
            if (colNumber === 3) {
                cell.numFmt = '₹#,##0.00';
            }
        });
    }

    // Total row
    worksheet.addRow([]);
    const totalRow = worksheet.addRow(['', 'Total:', totalAmount, '', '', '', '', '']);
    totalRow.getCell(2).font = { bold: true };
    totalRow.getCell(3).font = { bold: true };
    totalRow.getCell(3).numFmt = '₹#,##0.00';

    // Footer
    worksheet.addRow([]);
    worksheet.addRow([`Generated by: ${options.generatedBy}`]);
    worksheet.addRow([`Generated on: ${options.generatedAt}`]);

    const buffer = await workbook.xlsx.writeBuffer();
    return Buffer.from(buffer);
}
