// Legacy PDF export - kept for backward compatibility
// Simple PDF generation without external dependencies that may cause issues
// This creates a valid PDF structure manually

interface ReportData {
    title: string;
    subtitle?: string;
    generatedAt: string;
    generatedBy: string;
    fiscalYear: string;
    department: string;
    data: any[];
    totals?: Record<string, any>;
    columns: { key: string; header: string; width?: number; align?: 'left' | 'right' | 'center' }[];
}

export async function generatePDFReport(reportData: ReportData): Promise<Buffer> {
    // Build PDF content as text-based format
    const lines: string[] = [];

    // Header
    lines.push("JSPM's Rajarshi Shahu College of Engineering");
    lines.push("Department of Computer Science and Business Systems");
    lines.push("");
    lines.push("=".repeat(60));
    lines.push(reportData.title.toUpperCase());
    if (reportData.subtitle) {
        lines.push(reportData.subtitle);
    }
    lines.push("=".repeat(60));
    lines.push("");
    lines.push(`Fiscal Year: ${reportData.fiscalYear}`);
    lines.push(`Department: ${reportData.department}`);
    lines.push(`Generated: ${reportData.generatedAt}`);
    lines.push(`Generated By: ${reportData.generatedBy}`);
    lines.push("");
    lines.push("-".repeat(60));

    // Table header
    const headers = reportData.columns.map(col => col.header.padEnd(15)).join(" | ");
    lines.push(headers);
    lines.push("-".repeat(60));

    // Table data
    for (const row of reportData.data) {
        const rowData = reportData.columns.map(col => {
            const value = String(row[col.key] ?? '-');
            return value.substring(0, 15).padEnd(15);
        }).join(" | ");
        lines.push(rowData);
    }

    lines.push("-".repeat(60));

    // Totals if provided
    if (reportData.totals) {
        const totalsRow = reportData.columns.map(col => {
            const value = reportData.totals![col.key];
            return value !== undefined ? String(value).padEnd(15) : "".padEnd(15);
        }).join(" | ");
        lines.push("TOTALS: " + totalsRow);
    }

    lines.push("");
    lines.push("--- End of Report ---");

    const content = lines.join("\n");

    // Create a simple valid PDF
    const pdfContent = createSimplePDF(content, reportData.title);

    return Buffer.from(pdfContent);
}

function createSimplePDF(textContent: string, title: string): Uint8Array {
    // Create a minimal valid PDF structure
    const encoder = new TextEncoder();

    const pageContent = textContent
        .split('\n')
        .map((line, index) => `BT /F1 10 Tf 50 ${750 - index * 12} Td (${escapePDFString(line)}) Tj ET`)
        .join('\n');

    const streamContent = pageContent;
    const streamLength = encoder.encode(streamContent).length;

    const pdf = `%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj

2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj

3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>
endobj

4 0 obj
<< /Length ${streamLength} >>
stream
${streamContent}
endstream
endobj

5 0 obj
<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>
endobj

xref
0 6
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000266 00000 n 
0000000${(350 + streamLength).toString().padStart(3, '0')} 00000 n 

trailer
<< /Size 6 /Root 1 0 R >>
startxref
${400 + streamLength}
%%EOF`;

    return encoder.encode(pdf);
}

function escapePDFString(str: string): string {
    return str
        .replace(/\\/g, '\\\\')
        .replace(/\(/g, '\\(')
        .replace(/\)/g, '\\)')
        .replace(/[^\x20-\x7E]/g, ''); // Remove non-printable characters
}

export async function generateCSVReport(
    columns: { key: string; header: string }[],
    data: any[]
): Promise<string> {
    const headers = columns.map((col) => `"${col.header}"`).join(',');

    const rows = data.map((row) => {
        return columns
            .map((col) => {
                const value = row[col.key] ?? '';
                return `"${String(value).replace(/"/g, '""')}"`;
            })
            .join(',');
    });

    return [headers, ...rows].join('\n');
}
